server:
  port: 8080

spring:
  application:
    name: user-management
  datasource:
    url: jdbc:postgresql://localhost:5434/staging-users
    username: stadmin
    password: stadmin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration,classpath:staging/db/migration

security-cred:
  user: staginguser
  password: staginguser123